apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
spec:
  generators:
    - merge:
        mergeKeys:
          - server
          - app
          - name
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/vette1861/ArgoCDRollouts.git
                    revision: HEAD
                    files:
                    - path: helm-poc/charts/**/defaults.yaml
                - clusters:
                    values:
                      env: '{{ metadata.labels.env }}'
                      app: '{{ app }}'
                      chartName: '{{ chart.name }}'
                      chartVersion: '{{ chart.version }}'
                      namespace: '{{ namespace }}'
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/vette1861/ArgoCDRollouts.git
                    revision: HEAD
                    files:
                    - path: helm-poc/charts/**/overrides.yaml
                - clusters:
                    selector:
                      matchLabels: 
                        env: '{{ env }}'
                    values:
                      env: '{{ env }}'
                      app: '{{ app }}'
                      chartName: '{{ chart.name }}'
                      chartVersion: '{{ chart.version }}'
                      namespace: '{{ namespace }}'
  template:
    metadata:
      name: "{{ app }}-{{ name }}"
      labels:
        app: "{{ app }}"
    spec:
      project: default
      destination:
        server: '{{ server }}'
        namespace: '{{ values.namespace }}'
      source:
        helm:
          releaseName: '{{ values.chartName }}'
          valueFiles:
            - '../../values/{{ values.app }}/values-{{ values.env }}.yaml'
        path: 'helm-poc/charts/{{ values.app }}'
        repoURL: https://github.com/vette1861/ArgoCDRollouts.git
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
