apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - server
          - app
          - name
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/vette1861/ArgoCDRollouts.git
                    revision: HEAD
                    files:
                    - path: helm-poc/charts/**/defaults.yaml
                    - path: 'helm-poc/values/{{ values.path }}/values-{{ values.env }}.yaml'
                - clusters:
                    values:
                      env: '{{ metadata.labels.env }}'
                      app: '{{ app }}'
                      chartName: '{{ chart.name }}'
                      chartVersion: '{{ chart.version }}'
                      namespace: '{{ namespace }}'
                      basename: '{{ path.basename }}'
                      path: '{{path[0]}}'
                      valuesFile: '{{ values.yaml }}'
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/vette1861/ArgoCDRollouts.git
                    revision: HEAD
                    files:
                    - path: helm-poc/charts/**/overrides.yaml
                    - path: 'helm-poc/values/{{ values.path }}/values-{{ values.env }}.yaml'
                - clusters:
                    selector:
                      matchLabels: 
                        env: '{{ env }}'
                    values:
                      env: '{{ env }}'
                      app: '{{ app }}'
                      chartName: '{{ chart.name }}'
                      chartVersion: '{{ chart.version }}'
                      namespace: '{{ namespace }}'
                      basename: '{{ path.basename }}'
                      path: '{{path[0]}}'
                      valuesFile: '{{ values.yaml }}'
  template:
    metadata:
      name: "{{ app }}-{{ name }}"
      labels:
        app: "{{ app }}"
    spec:
      project: default
      destination:
        server: '{{ server }}'
        namespace: '{{ values.namespace }}'
      source:
        helm:
          valueFiles:
          - values.yaml
          values: |
            '{{ values.valuesFile }}'
          # parameters:
          # - name: commonLabels.env
          #   value: '{{ commonLabels.env }}'
          # - name: commonLabels.foo
          #   value: '{{ commonLabels.foo }}'
          # releaseName: '{{ values.chartName }}'
        # path: './{{ values.path }}/values/{{ values.basename }}'
        chart: '{{ values.chartName }}'
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: '{{ values.chartVersion }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
