apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - env
          - app
        generators:
          - git:
              repoURL: https://github.com/vette1861/ArgoCDRollouts.git
              revision: HEAD
              files:
              - path: charts/helm-poc/defaults.yaml
          - clusters:
              values:
                env: '{{ metadata.labels.env }}'
  template:
    metadata:
      name: 'helm-poc-{{ values.env }}'
      labels:
        app: "helm-poc"
    spec:
      project: default
      destination:
        server: "{{ server }}"
        namespace: helm-poc
      source:
        helm:
          valueFiles:
            - values/values-sandbox.yaml
          releaseName: metrics-server
        path: helm
        repoURL: https://charts.bitnami.com/bitnami # 5.11.7 # 6.2.1
        targetRevision: '{{ chart.version }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
