apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/vette1861/ArgoCDRollouts.git
        revision: HEAD
        files:
        - path: charts/helm-poc/defaults.json
  template:
    metadata:
      name: 'helm-poc-{{ env }}'
      labels:
        app: "helm-poc"
    spec:
      project: default
      destination:
        server: "{{ cluster.server }}"
        namespace: '{{ namespace }}'
      source:
        helm:
          valueFiles:
            - 'values/values-{{ env }}.yaml'
          releaseName: '{{ chart.name }}'
        path: helm
        repoURL: https://charts.bitnami.com/bitnami # 5.11.7 # 6.2.1
        targetRevision: '{{ chart.version }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
